### ISSUE TITLE
Feature Request: Add external sdcard as download directory option.

### ISSUE THREAD

**Issue by lexterror** [Tans5/tFileTransporter#10]
Hi Tans,

I would be great if you could add an option to use sdcard as download directory. It works in such apps as utorrent and 1DM+. Thank you!

**Comment by Tans5** [comment]
I will consider feature that custom download directory.

**Comment by Tans5** [comment]
2.3.0 has support custom download folder.

**Comment by lexterror** [comment]
Thank you Tans5!

**Comment by lexterror** [comment]
Tans it wont install! Did you make it 64bit only?

**Comment by lexterror** [comment]
Tans everything is fine! I was running out of space! Thank you!
