### ISSUE TITLE
mssing display in landscape mode

### ISSUE THREAD

**Issue by itsbrody** [Tans5/tFileTransporter#11]
I'm still playing around with tFileTransporter (found in on some FDroid store). Because I'm mainly and first checking it on my tablet, which I'm mainly using im landscape format I'm missing that the app display changing to the hardware justification (the setting to react is set to on). Would you please add this feature?

**Comment by Tans5** [comment]
No planning support landscope screen orientation.

**Comment by itsbrody** [comment]
Hmm....

Seems to be a operating system functionallity in Android. So, why not?

26.05.2023 11:57:22 Tans5 ***@***.***>:
