### ISSUE TITLE
error connecting android to pc

### ISSUE THREAD

**Issue by Faisal-c** [Tans5/tFileTransporter#12]
Hi Tans5,
when i connect two android phones to each other on a LAN the app works fine. but when i try connecting a phone and a pc selecting the pc as a server, the android app does find the pc and ip address but cant connect and throws **error -> Waiting Response timeout: 2000 ms.**
Am I missing something or the android version isn't supposed to be used in conjunction with the desktop version. Thanks.

**Comment by Tans5** [comment]
Please check Windows firewall, Use ping command to check phone and PC connection. Android phone need adb tools to use ping command.

**Comment by Faisal-c** [comment]
Thank you, Windows firewall was blocking it. It works well now
