### ISSUE TITLE
New feature request: provide copy command between the remote folder and the local folder, it can be implemented with the communication between two devices easily.

### ISSUE THREAD

**Issue by NanyangTaiji** [Tans5/tFileTransporter#18]

**Comment by NanyangTaiji** [comment]
It is a nice project indeed, keep working!

**Comment by Tans5** [comment]
你是中国人吗？

**Comment by Tans5** [comment]
你的意思是可以在：本地文件夹 -> 远端文件夹，远端文件夹 -> 本地文件夹，本地文件夹 -> 本地文件夹，远端文件夹 -> 远端文件夹 复制文件吗？

**Comment by NanyangTaiji** [comment]
本地文件夹 -> 远端文件夹，远端文件夹 -> 本地文件夹 就够了。

**Comment by Tans5** [comment]
写起来有点小麻烦，暂时也没有想到操作起来的 UI 怎么比较方便，考虑后续添加这个功能吧.

**Comment by NanyangTaiji** [comment]
本地文件夹 -> 远端文件夹，远端文件夹 -> 本地文件夹, 只要动态改变下载端的存储地。
