### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by AraafRoyall** [Tans5/tFileTransporter#21]
Show us a tutorial video to use wifi direct for share .

We don't understand this.
we need superfast speed

**Comment by Tans5** [comment]
1. Two devices open app, open GPS and WiFi.
2. Close eatch other.

Waiting two devices find eatch other and click device name, waiting connection create, after connection created, click `Transfer Files` button to transfer files.

**Comment by AraafRoyall** [comment]
Thanx its working.

you did a great job by making app simple 

can you make just few more changes 
• make an ui which shows transfer details like other shareing app
• make a button below this to share or send files 
• Can you anyhow reduce app size to use this on old devices

**Comment by Tans5** [comment]
Thanks for your advices.

**Comment by AraafRoyall** [comment]
👍 waiting for the update 
Thanks
