### ISSUE TITLE
Need information 

### ISSUE THREAD

**Issue by AraafRoyall** [Tans5/tFileTransporter#22]
1. [feat] Support handle other apps share request

whats this ?

is this used for receiving file from any other app like zapya or shareit.

or can you make a global app which support All apps to share and receive by this app.

hope you understand what i am trying to say 😴

**Comment by Tans5** [comment]
No，Other app (not FileTransfer app) can create a share request, tFileTransfer can handle this reqeust . For example Google Photo can reqeust share a photo to other device by tFileTransfer.

**Comment by Tans5** [comment]
![Screenshot_20241121_181209](https://github.com/user-attachments/assets/4764d798-15a2-4325-b81b-0a6a453155ca)

**Comment by Tans5** [comment]
![Screenshot_20241121_181054](https://github.com/user-attachments/assets/81232ec8-1e58-4f08-9417-41ba784526c6)

**Comment by Tans5** [comment]
![Screenshot_20241121_181122](https://github.com/user-attachments/assets/a7d4fd58-a383-455d-bee7-18ed3a9f1b08)

**Comment by AraafRoyall** [comment]
.


For your kind of information 

do you know about mi share or xiaomi share 

it can connects to many other company share like oppo vivo.

i asking that mechanism

**Comment by AraafRoyall** [comment]
![Screenshot_2024-11-21-15-46-36-414_com.miui.mishare.connectivity.jpg](https://github.com/user-attachments/assets/5193aa03-198a-4e2e-bb85-dc1b86c5e358)

.


For your kind of information 

do you know about mi share or xiaomi share 

it can connects to many other company share like oppo vivo.

i asking that mechanism

**Comment by AraafRoyall** [comment]
![Screenshot_2024-11-21-15-47-09-447_com.miui.mishare.connectivity.png](https://github.com/user-attachments/assets/a7cb95fa-2f67-4f4f-9691-e1f254ee4131)

**Comment by Tans5** [comment]
Can't create connection to other company share app, it's too hard.

**Comment by Tans5** [comment]
The smart phone company share app is not open source and i don't known it's file transfer protocol.

**Comment by AraafRoyall** [comment]
ok
