### ISSUE TITLE
The app would be exceptionally more convenient out of local network

### ISSUE THREAD

**Issue by TadiT7** [Tans5/tFileTransporter#3]
Basically, I'm seeking for something matching the description of Syncthing Lite, and it's nowhere to be found (while that app seems to be just dead, where full-fledged Syncthing forces on you complete syncing over casual browsing or single file operation). Needing to always be in a local network is a burden that introduces limitations that don't have to exist, and decentralized file sharing over P2P would be crucial to push the wider audience from commercial cloud hosting. This app basically looks like everything what I really need, but I can't VPN to home 24/7 :/ Probably an overkill would be to base it on .onion domain, but even that would improve versatility. For extra reference of decentralized packet transfer, I can also name Tox and Briar communicators. Sorry for bothering if you see this project as permanently based on local network, but just posting my unfulfilled dreams. Thanks!

**Comment by TadiT7** [comment]
Random keywords: UDP hole punching, DHT, BitTorrent, ssh-p2p

**Comment by Tans5** [comment]
This apps just a tools could share files for Android devices and PCs, you could do that over local area network or WIFI P2P. It's not a Cloud Disk.

**Comment by Tans5** [comment]
It's more alike a invisible USB cable to connect diffrent devices.

**Comment by TadiT7** [comment]
I know what it's able to do, but pretty sure it'd be helpful (at least for me) to make it work out of local network. In my usage it'd handle many of cloud usecases, as for me it's mostly about quick access to files that aren't present on one of my devices (keeping them completely in sync would also clog their storage too much). This idea seems to be targeted by Syncthing Lite, but as I mentioned initially, it seems to be an abandoned project, while classic Syncthing forces complete sync.
