### ISSUE TITLE
v2.1.0 adds proprietary components and tracking, increasing APK size by more than factor 5

### ISSUE THREAD

**Issue by IzzySoft** [Tans5/tFileTransporter#8]
Looks like your adding of QR Code creation had some very unwanted side effects:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* ML Kit (/com/google/mlkit): NonFreeDep,Tracking

3 offenders.
```

The trouble-maker here is MLKit, which drags in the other two – so essentially I'd have to add 3 anti-features which would scare potentially interested people away from your app: `NonFreeNet`, `NonFreeDep` and `Tracking`. Instead, I've just rolled back the latest updated and disabled its daily update checks in the hope you can find a free replacement. Not sure what your requirements are there, but why wouldn't e.g. ZXing an option? If not, could you maybe at least offer a FOSS flavor coming without those proprietary components? Thanks in advance!

**Comment by Tans5** [comment]
v2.1.0 Add `CameraX`, `MLKit-Barcode-Scannning` and `QRCodeGen`:  

```Groovy

    // CameraX
    def camerax_version = "1.2.2"
    implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"
    implementation "androidx.camera:camera-lifecycle:${camerax_version}"
    implementation "androidx.camera:camera-video:${camerax_version}"
    implementation "androidx.camera:camera-view:${camerax_version}"
    implementation "androidx.camera:camera-extensions:${camerax_version}"

    // BarcodeScan
    implementation 'com.google.mlkit:barcode-scanning:17.1.0'

    // QRCode Gen
    implementation 'com.github.kenglxn.QRGen:android:3.0.1'
    // implementation 'com.github.kenglxn.QRGen:javase:3.0.1'
```
The native libs of those dependencies cause a big APK size increasing:
<img width="848" alt="截屏2023-05-16 上午11 28 09" src="https://github.com/Tans5/tFileTransporter/assets/20902178/caa6cbea-98da-4120-a312-6ff4395d60ca">
Android Studio would remove unuse Java code when build a release apk, so Java code is not the main problem.  

I need most Android devices could use this app, so default apk do not set abi filters and it caused apk size big increasing. You can built apk with abiFilters or [Get It On Google Play](https://play.google.com/store/apps/details?id=com.tans.tfiletransporter).

**Comment by IzzySoft** [comment]
I cannot build (I'm not an Android dev and neither do I have a build environment) – nor can I "get it on Google Play" as I intentionally have no Google account (and no device with Google Services on them). And as a user, should I feel a QR code generator worth a five-times size increase? I personally would not – especially when seeing there are QR Code reader/generator combos coming at much smaller sizes than MLKit increased the size of your app.

As for the native code: one could use per-ABI builds AFAIK. But my main concern however are the proprietary components, which effectively render your app non-free. And the dependency on GMS probably even prevents it on devices which intentionally do NOT have Google Services installed – which then contradicts the "need most Android devices could use this app" point (for that, a library like ZXing which does not depend on non-free stacks should be preferred in general :wink:)

**Comment by Tans5** [comment]
I built apks for each cpu architecture，hope it could solve your problem. 😊[v2.1.0](https://github.com/Tans5/tFileTransporter/releases)

**Comment by Tans5** [comment]
For most of Android devices, choose arm64 is ok.

**Comment by IzzySoft** [comment]
> I built apks for each cpu architecture，hope it could solve your problem

Thanks! Those alleviate the size issue (still factor 2.5), but not the main issue with the proprietary libraries:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* ML Kit (/com/google/mlkit): NonFreeDep,Tracking

3 offenders.
```

Can something be done about those as well?

> For most of Android devices, choose arm64 is ok.

Not quite correct, but if you wish that can be done. While only very few 64bit devices (e.g. the Pixel 7 plus) do not support 32bit apps, not a single 32bit device supports 64bit apps (naturally). Further, with arm64 already being beyond 10 MB per APK, I will only keep the last 2 versions then (with armeabi at below 9 MB I'd keep 3 – and with a FOSS build flavor coming without MLKit & deps, probably 3 of the "fat APK" supporting all 4 ABIs).

**Comment by IzzySoft** [comment]
Scanning the latest APK:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* ML Kit (/com/google/mlkit): NonFreeDep,Tracking

3 offenders.
```

APK size is in the limit for me to keep 1 version in my repo, but the issue with the non-free dependencies is still unsolved. Is there a chance to get it solved?

**Comment by IzzySoft** [comment]
@Tans5 any word?
