### ISSUE TITLE
local folder is only the internal memory

### ISSUE THREAD

**Issue by itsbrody** [Tans5/tFileTransporter#9]
while playing around with tfiletransfer (on android) against tfiletransfer_desktop I discovered that the topmost level is the level of the internal memory (only), while e.g. a file browser shows an level above,which can select internal and external memory, then.

Because the external memory is often the bigger one, is it possible take tfiletransporter the ability (maybe switchable) to go one level up?

**Comment by lexterror** [comment]
I have the same issue. No sdcard option. Could you please add this feature. Thank you!

**Comment by Tans5** [comment]
I wiil add this feature in next version.

**Comment by Tans5** [comment]
v2.2.0 already support SD Card's files share.

**Comment by lexterror** [comment]
It works! Like you said they both have to be v2.2.0!

Thank you!!!

**Comment by Tans5** [comment]
😊

**Comment by lexterror** [comment]
Tans5, do you think you could add external as download directory as well? I dont want to open new issue!
